version: "3.3"

services:
  mysql:
    container_name: mysql
    build:
      dockerfile: Dockerfile
      context: ./mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
  edelivery:
    container_name: edelivery
    build:
      dockerfile: Dockerfile
      context: ./tomcat
    image: edelivery:latest
    command: dockerize -wait tcp://mysql:3306 -timeout 20s
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      - mysql
