version: "3"

services:
  mysql:
    container_name: mysql
    build: ../mysql
    cap_add:
      - SYS_NICE
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
  domibus:
    container_name: domibus
    build: ../tomcat
    command: dockerize -wait tcp://mysql:3306 -timeout 20s
    ports:
      - "8080:8080"
    depends_on:
      - mysql
