version: "3"

services:
  db:
    container_name: db
    build: ../mysql
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=domibus
      - MYSQL_USER=edelivery
      - MYSQL_PASSWORD=edelivery
    expose:
      - "3306"
  server:
    container_name: server
    build: ../tomcat
    command: dockerize -wait tcp://mysql:3306 -timeout 20s
    ports:
      - "8080:8080"
    depends_on:
      - db
